identity = "myuser@wallet000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
version = 1
initial_state = [0, 0, 0, 0]
initial_state_len = 4
next_state = [0, 0, 0, 0]
next_state_len = 4
identity_len = 13
tx_hash = "3b8f91a7ea6e74505d473b95080e6f51a60e2bacaf0ce4472462c2718b7428f8"
tx_hash_len = 64
index = 0
blob_number = 1
blob_index = 0
blob_contract_name_len = 12
blob_contract_name = "check_secret0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
blob_capacity = 32
blob_len = 32
blob = [
  178,
  12,
  109,
  180,
  36,
  113,
  78,
  119,
  34,
  140,
  156,
  29,
  19,
  168,
  171,
  177,
  252,
  102,
  127,
  120,
  29,
  62,
  14,
  163,
  215,
  226,
  14,
  13,
  136,
  30,
  122,
  97,
]
tx_blob_count = 3
success = 1
password = [
  54,
  125,
  167,
  67,
  149,
  179,
  197,
  50,
  167,
  34,
  58,
  66,
  98,
  211,
  27,
  151,
  103,
  229,
  51,
  177,
  232,
  184,
  99,
  221,
  143,
  162,
  126,
  153,
  189,
  60,
  232,
  66,
]
