[package]
name = "check_jwt"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.2.0", git = "https://github.com/noir-lang/poseidon" }
jwt = { git = "https://github.com/zkemail/noir-jwt", tag = "v0.5.1" }
noir_utils = { path = "../noir-utils" }
