[package]
name = "check_jwt"
type = "bin"
authors = [""]

[dependencies]
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
jwt = { tag = "saleel/deps-update-beta11", git = "https://github.com/zkemail/noir-jwt" }
